### ISSUE TITLE
怎么没生成可执行文件‘go-tun2socks‘？

### ISSUE THREAD

**Issue by luckypoem** [dosgo/go-tun2socks#2]
cd $GOPATH

yudeMacBook-Air:gopath brite$ go get -u -v github.com/dosgo/go-tun2socks/
yudeMacBook-Air:gopath brite$ which go-tun2socks
yudeMacBook-Air:gopath brite$

**Comment by dosgo** [comment]
源码，没有main文件。。。不能直接使用
